- platform: yr
  name: Weather
  forecast: 24
  monitored_conditions:
    - temperature
    - symbol
    - precipitation
    - windSpeed
    - pressure
    - windDirection
    - humidity
    - fog
    - cloudiness
    - lowClouds
    - mediumClouds
    - highClouds
    - dewpointTemperature

- platform: moon

- platform: template
  sensors:
    solar_angle:
      friendly_name: "Sun angle"
      unit_of_measurement: 'degrees'
      value_template: "{{ states.sun.sun.attributes.elevation }}"

    sunrise:
      friendly_name: "Sunrise"
      value_template: '{{ as_timestamp(states.sun.sun.attributes.next_rising)  | timestamp_custom("%H:%M") }}'

    sunset:
      friendly_name: "Sunset"
      value_template: '{{ as_timestamp(states.sun.sun.attributes.next_setting)  | timestamp_custom("%H:%M") }}'

    light_auto_on_time:
      friendly_name: 'Lights will turn on at'
      value_template: '{{ (as_timestamp(states.sun.sun.attributes.next_setting) - (states("input_number.light_auto_on_time") | int)  * 60)  | timestamp_custom("%H:%M") }}'

    light_auto_off_time:
      friendly_name: 'Lights will turn off at'
      value_template: '{{ "%0.02d:%0.02d" | format(states("input_number.light_auto_off_hour") | int, states("input_number.light_auto_off_minutes") | int) }}'
